service: serverless-contact

provider:
  name: aws
  runtime: nodejs6.10

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          path: contact
          method: post
          cors: true
